//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_GiuXe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HinhAnh {
            get {
                return ((string)(this["HinhAnh"]));
            }
            set {
                this["HinhAnh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuPhong {
            get {
                return ((string)(this["DuPhong"]));
            }
            set {
                this["DuPhong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_1 {
            get {
                return ((string)(this["Camera_IP_Trai_1"]));
            }
            set {
                this["Camera_IP_Trai_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_2 {
            get {
                return ((string)(this["Camera_IP_Trai_2"]));
            }
            set {
                this["Camera_IP_Trai_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_Cong_1 {
            get {
                return ((string)(this["Camera_IP_Trai_Cong_1"]));
            }
            set {
                this["Camera_IP_Trai_Cong_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_Cong_2 {
            get {
                return ((string)(this["Camera_IP_Trai_Cong_2"]));
            }
            set {
                this["Camera_IP_Trai_Cong_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_TaiKhoan_1 {
            get {
                return ((string)(this["Camera_IP_Trai_TaiKhoan_1"]));
            }
            set {
                this["Camera_IP_Trai_TaiKhoan_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_TaiKhoan_2 {
            get {
                return ((string)(this["Camera_IP_Trai_TaiKhoan_2"]));
            }
            set {
                this["Camera_IP_Trai_TaiKhoan_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_MatKhau_1 {
            get {
                return ((string)(this["Camera_IP_Trai_MatKhau_1"]));
            }
            set {
                this["Camera_IP_Trai_MatKhau_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Trai_MatKhau_2 {
            get {
                return ((string)(this["Camera_IP_Trai_MatKhau_2"]));
            }
            set {
                this["Camera_IP_Trai_MatKhau_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_1 {
            get {
                return ((string)(this["Camera_IP_Phai_1"]));
            }
            set {
                this["Camera_IP_Phai_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_2 {
            get {
                return ((string)(this["Camera_IP_Phai_2"]));
            }
            set {
                this["Camera_IP_Phai_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_TaiKhoan_1 {
            get {
                return ((string)(this["Camera_IP_Phai_TaiKhoan_1"]));
            }
            set {
                this["Camera_IP_Phai_TaiKhoan_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_TaiKhoan_2 {
            get {
                return ((string)(this["Camera_IP_Phai_TaiKhoan_2"]));
            }
            set {
                this["Camera_IP_Phai_TaiKhoan_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_MatKhau_1 {
            get {
                return ((string)(this["Camera_IP_Phai_MatKhau_1"]));
            }
            set {
                this["Camera_IP_Phai_MatKhau_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_MatKhau_2 {
            get {
                return ((string)(this["Camera_IP_Phai_MatKhau_2"]));
            }
            set {
                this["Camera_IP_Phai_MatKhau_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocThe_Trai {
            get {
                return ((string)(this["DocThe_Trai"]));
            }
            set {
                this["DocThe_Trai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocThe_Phai {
            get {
                return ((string)(this["DocThe_Phai"]));
            }
            set {
                this["DocThe_Phai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_Cong_1 {
            get {
                return ((string)(this["Camera_IP_Phai_Cong_1"]));
            }
            set {
                this["Camera_IP_Phai_Cong_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_IP_Phai_Cong_2 {
            get {
                return ((string)(this["Camera_IP_Phai_Cong_2"]));
            }
            set {
                this["Camera_IP_Phai_Cong_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Chuoi_Trai_1 {
            get {
                return ((string)(this["Camera_Chuoi_Trai_1"]));
            }
            set {
                this["Camera_Chuoi_Trai_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Chuoi_Trai_2 {
            get {
                return ((string)(this["Camera_Chuoi_Trai_2"]));
            }
            set {
                this["Camera_Chuoi_Trai_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Chuoi_Phai_1 {
            get {
                return ((string)(this["Camera_Chuoi_Phai_1"]));
            }
            set {
                this["Camera_Chuoi_Phai_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Chuoi_Phai_2 {
            get {
                return ((string)(this["Camera_Chuoi_Phai_2"]));
            }
            set {
                this["Camera_Chuoi_Phai_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Hang_Trai_1 {
            get {
                return ((string)(this["Camera_Hang_Trai_1"]));
            }
            set {
                this["Camera_Hang_Trai_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Hang_Trai_2 {
            get {
                return ((string)(this["Camera_Hang_Trai_2"]));
            }
            set {
                this["Camera_Hang_Trai_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Hang_Phai_1 {
            get {
                return ((string)(this["Camera_Hang_Phai_1"]));
            }
            set {
                this["Camera_Hang_Phai_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_Hang_Phai_2 {
            get {
                return ((string)(this["Camera_Hang_Phai_2"]));
            }
            set {
                this["Camera_Hang_Phai_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaudRate {
            get {
                return ((string)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\LTH;Initial Catalog=Bai_Xe_TM;User ID=sa;Password=sa2012")]
        public string Connect {
            get {
                return ((string)(this["Connect"]));
            }
            set {
                this["Connect"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\LTH;Initial Catalog=Bai_Xe_TM;User ID=sa;Password=sa2012")]
        public string Bai_Xe_TMConnectionString2 {
            get {
                return ((string)(this["Bai_Xe_TMConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\LTH;Initial Catalog=Bai_Xe_TM;User ID=sa;Password=sa2012")]
        public string Bai_Xe_TMConnectionString3 {
            get {
                return ((string)(this["Bai_Xe_TMConnectionString3"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Full {
            get {
                return ((string)(this["Full"]));
            }
            set {
                this["Full"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Diff {
            get {
                return ((string)(this["Diff"]));
            }
            set {
                this["Diff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Log {
            get {
                return ((string)(this["Log"]));
            }
            set {
                this["Log"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderBackUp {
            get {
                return ((string)(this["FolderBackUp"]));
            }
            set {
                this["FolderBackUp"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\LTH;Initial Catalog=Bai_Xe_TM;User ID=sa;Password=sa2012")]
        public string Bai_Xe_TMConnectionString {
            get {
                return ((string)(this["Bai_Xe_TMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\LTH;Initial Catalog=Bai_Xe_TM;User ID=sa;Password=sa2012")]
        public string Bai_Xe_TMConnectionString1 {
            get {
                return ((string)(this["Bai_Xe_TMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\LTH;Initial Catalog=Bai_Xe_TM;User ID=sa;Password=sa2012")]
        public string Bai_Xe_TMConnectionString4 {
            get {
                return ((string)(this["Bai_Xe_TMConnectionString4"]));
            }
        }
    }
}
